// Builds each MCP Apps card into one self-contained HTML file (scripts and CSS
// inlined), then embeds them in src/mcp/ui-bundle.generated.ts so the hub
// serves them with no file-system access (works unchanged on AWS Lambda).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';

const uiDir = dirname(fileURLToPath(import.meta.url));
const cards = ['screening', 'today', 'pause', 'timeline'];
const html = {};

for (const card of cards) {
  await build({
    root: uiDir,
    logLevel: 'warn',
    configFile: false,
    plugins: [viteSingleFile()],
    build: {
      outDir: join(uiDir, 'dist', card),
      emptyOutDir: true,
      target: 'es2022',
      rollupOptions: { input: join(uiDir, `${card}.html`) },
    },
  });
  html[card] = readFileSync(join(uiDir, 'dist', card, `${card}.html`), 'utf8');
  console.log(`  ✓ ${card.padEnd(10)} ${(html[card].length / 1024).toFixed(1)} KB`);
}

const out = join(uiDir, '..', 'src', 'mcp', 'ui-bundle.generated.ts');
writeFileSync(
  out,
  `// GENERATED by ui/build.mjs — do not edit. Rebuild with: npm run build:ui -w @kinwise/hub\n` +
    `export const UI_HTML = ${JSON.stringify(html, null, 2)} as const;\n`,
);
console.log(`  → ${out}`);
